export const VOTE_DURATION_SECONDS = 60;
export const VOTE_DEFAULT_PASS_RATIO = 60;
export const VOTE_DEFAULT_MIN_VOTES = 3;
export const VOTE_DEFAULT_COOLDOWN_SECONDS = 300;

export const MAX_ZIP_FILE_SIZE = 100 * 1024 * 1024;
export const MAX_CONCURRENT_REQUESTS = 5;

export const SERVER_NAME_CACHE_TTL = 60000;

export const RCON_RECONNECT_BASE_DELAY_MS = 1000;
export const RCON_RECONNECT_MAX_DELAY_MS = 30000;
export const RCON_RECONNECT_BACKOFF_MULTIPLIER = 2;
export const RCON_RECONNECT_MAX_ATTEMPTS = 10;

export const LOG_POLL_INTERVAL = 2000;

export const SCHEDULER_LOG_CHECK_INTERVAL = 5000;
export const SCHEDULER_PERIODIC_INTERVAL = 1000;

export const RATE_LIMIT_STRICT_MAX = 10;
export const RATE_LIMIT_STRICT_WINDOW_MS = 60000;
export const RATE_LIMIT_DEFAULT_MAX = 100;
export const RATE_LIMIT_DEFAULT_WINDOW_MS = 60000;

export const WS_PING_INTERVAL = 30000;

export const MAX_BACKUP_COUNT = 20;

export const MAX_LOG_SIZE = 50 * 1024 * 1024;
export const MAX_LOG_FILES = 5;
